version: "3.9"

services:
  # -------------------------
  # PostgreSQL Database
  # ---------------clear----------
  db:
    image: postgres:16
    container_name: ai_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
#    ports:
#      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  # -------------------------
  # FastAPI Backend
  # -------------------------
  backend:
    build: ./backend
    container_name: ai_backend
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: unless-stopped

  # -------------------------
  # Next.js Frontend
  # -------------------------
  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}   # 👈 pass through from .env
    container_name: ai_frontend
    env_file:
      - ./.env
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: unless-stopped



# -------------------------
# Persistent volume for DB
# -------------------------
volumes:
  dbdata:
